export enum ValidateRegisterErrors {
  USERNAME_LENGTH = 'USERNAME LENGTH',
  USERNAME_MASK = 'USERNAME MASK',
  PASSWORD_LENGTH = 'PASSWORD LENGTH',
  PASSWORD_MASK = 'PASSWORD MASK',
  PASSWORD_MATCHES = 'PASSWORD MATCHES',
  NO_DATA = 'NO DATA',
  SERVER_ERROR = 'server error in registerByUsername (AsyncThunk)'
}
